version: '3.1'

services:
  mongo:
    image: mongo:3.2.4
    ports: ["27018:27017"]
    environment: ["MONGO_INITDB_DATABASE=proximus-demo"]
    command: -smallfiles
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:27018"]
      interval: 30s
      timeout: 10s
      retries: 5

  mongo-client:
    image: mongoclient/mongoclient
    ports: ["3030:3000"]
    environment: ["MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo/proximus-demo?useSSL=false&allowPublicKeyRetrieval=true"]
    links: [mongo]
    restart: always
    depends_on:
      - mongo

  app:
    image: myapp/proximus-backend-app
    ports: ["8091:8090"]
    environment: ["SPRING_DATASOURCE_URL=jdbc:mongodb://mongo/proximus-demo?useSSL=false&allowPublicKeyRetrieval=true"]
    links: [mongo]
    entrypoint: "java -Djava.security.egd=file:/dev/./urandom -jar /app.jar"
    restart: always
    depends_on:
      - mongo
